### ISSUE TITLE
Design Feedback: Responsive Layout Switcher

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#102]
@radu-themeisle @stefan-cotitosu @selul 

I was thinking of changing how the current Responsive Switcher looks, which is:

![Otter](https://user-images.githubusercontent.com/2649903/57055931-6b381600-6cbc-11e9-8191-fec895a382ac.gif)

Here are few examples of how other plugins are doing it:

Elementor: It's very simple:

![Elementor](https://user-images.githubusercontent.com/2649903/57055970-c407ae80-6cbc-11e9-8617-d24e772bd3af.gif)

Kadence: It's simple but three choices are always visible that I find to be weird:

![Kadence](https://user-images.githubusercontent.com/2649903/57055975-d5e95180-6cbc-11e9-833b-bbd686fb538a.gif)

Beaver: It's too simple and I find it a little confusing. Took me some time to realize the icon change:

![Beaver](https://user-images.githubusercontent.com/2649903/57055983-e7325e00-6cbc-11e9-92f2-6aea5f39285a.gif)

Won't name the plugin, but I found it to be funny so sharing:

![Azexo](https://user-images.githubusercontent.com/2649903/57055994-f1ecf300-6cbc-11e9-8ad0-dfd720344fb2.gif)

Or do you think the current one is better? Maybe we can improve the current design if you've something in mind?

**Comment by radu-themeisle** [comment]
@HardeepAsrani from the options you presented I think the current responsive switcher is just fine and I don't see why you want to change it 😃.
The key advantages are that this design allows the icon to be as large as possible while also keeping the interface clean.

The rest of the plugins have very small icons (I'm not taking into considerations the Beaver example and the "plugin which its name we will not mention" as they are very bad) and I think they are based only on the fact that users are used to them (I don't know if for example prior to what Elementor has done somebody else had a solution to display responsive switchers).

If you still feel that "something needs to be changed" my only idea would be to put the switcher inline with the controls, but I'm guessing either Gutenberg doesn't allow it (what does it allow anyway 😂) and/or the limited width of the sidebar would make everything look cramped.

**Comment by HardeepAsrani** [comment]
> If you still feel that "something needs to be changed" my only idea would be to put the switcher inline with the controls.

Can you explain? @radu-themeisle

**Comment by radu-themeisle** [comment]
@HardeepAsrani something like this (I can already hear in my head: "Gutenberg doesn't allow this" 😂)
![Screenshot_1](https://user-images.githubusercontent.com/36160208/57125372-e3244000-6d91-11e9-871d-7a27d1b103fd.png)

**Comment by HardeepAsrani** [comment]
@radu-themeisle 

1. Gutenberg can allow it but our implementation doesn't allow it as we don't write the switcher for each control separately so it appears next to the title in all controls. (I know, it's the same version of that 😛 )

2. Even if it allowed it, it will be bad because the padding thing already takes too much space. If you enter a number like 250 then won't see the last digit of it. :(

**Comment by selul** [comment]
@HardeepAsrani I find the current solution is pretty solid and I won't change it.
Moreover, I think would worth to check in the future how we can improve the responsive switcher preview experience.

**Comment by HardeepAsrani** [comment]
@selul I tried to do that, like Elementor and Customizer, where the screen shrinks to provide a preview. Didn't go well so left it for the future.

Closing this ticket as `wontfix`.
