### ISSUE TITLE
Removing Deprecated Blocks

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#103]
There are some legacy blocks in Otter, [such as Notice, Click to Tweet and Chart](https://github.com/Codeinwp/gutenberg-blocks/tree/master/src/blocks/deprecated), which we need to remove.

I was hoping to remove it in the middle of 2019, but still, around 8% users use 1.0 version of Otter, and a lot of have recently migrated from 1.0 to 1.1, which makes me think a lot of users are still using older blocks.

For now, I'm thinking of moving forward with this when the active installs for 1.0 are less than 1% or in 3-4 months.

**Comment by HardeepAsrani** [comment]
I'm planning on removing the blocks which we added in the first version that we removed later for users to add new ones, such as Notice, Click to Tweet, Chart and such. It's been more than a year so shouldn't cause many issues. What do you think? @selul

**Comment by selul** [comment]
yes, looks good to me
