### ISSUE TITLE
Lazy Loading & Code Splitting

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#112]
At some point, we better start doing code splitting to improve the package size: https://webpack.js.org/guides/lazy-loading/

**Comment by HardeepAsrani** [comment]
Due to the .json file of Font Awesome, which contained a list of all FA icon, the size of the initial load used to be a total of around 2.9mb.

With code splitting and `React.Lazy`, the 2.5mb of FA .json file will now load on request when a block with Font Awesome is loaded.

In the future, we can abstract things out and load more things dynamically to improve the page load speed in the editor.

cc @selul @ineagu 

<img width="598" alt="Screen Shot 2019-08-02 at 6 33 00 am" src="https://user-images.githubusercontent.com/2649903/62337440-42f5c880-b4f2-11e9-89ab-7b12a98338f4.png">

**Comment by selul** [comment]
@HardeepAsrani why now is not a good time?

**Comment by HardeepAsrani** [comment]
What do you mean @selul ?

**Comment by selul** [comment]
I'm talking about this phrase 

> In the future, we can abstract things out and load more things dynamically to improve the page load speed in the editor.

**Comment by HardeepAsrani** [comment]
@selul It won't affect more than 20-30kbs for the current setup. And it's not ideal for everything to load dynamically either. So instead of rushing with this, it's better to wait and think about how it will work.

We can move load Template Library and Drag & Drop in Post Grid to lazy loading.

**Comment by selul** [comment]
I'm talking about the FontAwesome thing, or is that included already?

**Comment by HardeepAsrani** [comment]
Yes, that I have done. That was the only major package. 2.5mb. Apart from it, each file is like 2-3kb each. :)

**Comment by selul** [comment]
Yes, makes sense.
