### ISSUE TITLE
Support for CPT in Post Grid

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#116]
We will have to find a way to support custom post types in the post grid. Not sure so maybe it should be experimental at this stage.

**Comment by HardeepAsrani** [comment]
What do you think about this one? Should we do this one soon or leave it for later? @selul

**Comment by selul** [comment]
yes,  we can start working on it.

**Comment by HardeepAsrani** [comment]
@selul Will it be fine if it only works for post types which are registered in rest?

**Comment by selul** [comment]
sounds good to me.
