### ISSUE TITLE
Template Library outside Section Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#120]
As most of the block plugins are doing, they give an option to import templates from Template Library without a Section Block. They use these three approaches:

- A Template Library block, which it serves no purpose and it's just like using the Section Block.
- A button on the top bar, which seems really good way but I also feel it's a burden to always see it there as most people won't be using it so many times to have it on the top always.
- A button on the Plugin Menu which seems a good option but is not visible.

What do you think? Do we need to do it?

![Template Library](https://user-images.githubusercontent.com/2649903/63211787-933b7000-c119-11e9-9242-c5b8b4b563f5.png)

@selul @ineagu

**Comment by selul** [comment]
@HardeepAsrani what's wrong with the current approach?

**Comment by HardeepAsrani** [comment]
@selul Nothing really, that's why this one is just for feedback. A way to put Template Library on focus outside the Section block.

**Comment by selul** [comment]
None of the seems better for me. Only the 1st version maybe. 

One thing that has some room for improvement is the design/size of the template library button, which seems too big compared with the `Publish` button for instance

**Comment by HardeepAsrani** [comment]
Alright, 1st one is as good as Section block already so we can skip it. :D
