### ISSUE TITLE
Improve CSS workflow

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#123]
# CSS Workflow Improvements

We are breaking the CSS workflow to make it more flexible and structured. This will be part of the next update of Otter.

## Current Workflow & Problems

Currently, we have the main class of library handling everything which makes it big and complicated to maintain.

We also generate all the CSS from blocks when rendering it on the front-end, which has performance issues given the code runs every time the page is loaded, and the styles are added on fold which isn't ideal. It can also be an issue when we update the block's HTML structure when older versions of the block are served CSS for thee newer version.

## Solution

With the new workflow, we will have a main class handling all the logic and methods for handling the CSS, and separate classes for each block to handle their own CSS code, making the code more modular and easy to maintain.

We will also minify & store code in the post meta instead of handling it with every request, that should increase the performance of the code. Once this is done, we can also save the CSS file with the CSS in media library and load it from there to remove inline CSS loaded in the header.

It will be like this:

- Check if meta exists & CSS file exist, if it does then load it.
- If the meta doesn't exist, then load the inline CSS & run the task to build the meta/file.

### Things to consider

- [x] We need to make sure that it works fine with Reusable Blocks, which can cause an issue. We can load them inline or have their CSS in their meta.
- [x] We should load CSS inline when the user is previewing the post, instead of loading the CSS or from meta.
- [x] Make sure it works fine with AMP.
- [x] Make sure it works fine when blocks are loaded outside the single page.
- [x] We need to make sure that Neve/Hestia is also updated keeping the new workflow in mind, as they use the render CSS function in Header/Footer builder.
- [x] Until Hestia/Neve are ready, we can perhaps have a deprecated function in Otter to handle it?

Any other concerns? Leave a comment.

**Comment by selul** [comment]
I don't understand what has to do Hestia & Neve to this?

**Comment by HardeepAsrani** [comment]
@selul Hestia/Neve use one of the functions of Otter in Header/Footer builder to make sure the CSS is generated even when our blocks are loaded in the header/footer.

**Comment by HardeepAsrani** [comment]
Fixed in https://github.com/Codeinwp/gutenberg-blocks/pull/119
