### ISSUE TITLE
More control over meta in Posts Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#124]
I can see soon users will ask, as some have asked already, to edit post date, category or description length. We need to make sure the UI is not complicated.

**Comment by HardeepAsrani** [comment]
There are two prototypes for this:

First:

![Meta One](https://user-images.githubusercontent.com/2649903/65973049-54bf0200-e488-11e9-92f3-5e99c2db72d9.gif)

Second:

![Meta Two](https://user-images.githubusercontent.com/2649903/65973064-5be61000-e488-11e9-9b8d-6389f92e642a.gif)


What do you think? Which one do you like, or do you have something better in mind? @cosmin-serbanescu @rodica-andronache @selul @abaicus @cristian-ungureanu

**Comment by HardeepAsrani** [comment]
Keep in mind that UI for Markers in Maps Block looks like this:

![Map UI](https://user-images.githubusercontent.com/2649903/65981338-7fb05280-e496-11e9-871b-a35422277fd5.gif)

**Comment by cosmin-serbanescu** [comment]
I personally like the first approach - without having to go back & forth through those.

**Comment by abaicus** [comment]
The first approach seems more intuitive in terms of UX for me too.

**Comment by cristian-ungureanu** [comment]
First approach.

**Comment by HardeepAsrani** [comment]
In reality, here's the final product:

![Post UI](https://user-images.githubusercontent.com/2649903/66050208-649f1a80-e54a-11e9-9615-77ee905ab582.gif)

Some items have additional options and some don't which makes the UI bit uneasy to look at. Any feedback? :D

**Comment by cosmin-serbanescu** [comment]
I don't see it an 'uneasy' and probably replacing the pen icon with a chevron-down makes more sense. Otherwise, looking great.

**Comment by abaicus** [comment]
I think it's better than the two-click approach. @cosmin-serbanescu is right. A chevron might be more consistent. Maybe also automatically close other fields when one is opened.

**Comment by HardeepAsrani** [comment]
Done. Thanks for the review. :)
