### ISSUE TITLE
Duplicated post content on the Blog page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/gutenberg-blocks#127]
Steps to reproduce :
- Install Neve or Twenty Nineteen ( other themes as well )
- Create a post in Otter with this block https://prnt.sc/pb7n08
- add a _Read More_ block after Our Blog https://prnt.sc/pb7nen
- Check the Blog page and you will see the content duplicated https://prnt.sc/pb7o6q

@HardeepAsrani

**Comment by HardeepAsrani** [comment]
Good & bad news:

- Bad: It's indeed an issue.
- Good: It's an issue with Gutenberg and not with Otter.

Closing this here and opening it in Gutenberg repo. @rodica-andronache

**Comment by HardeepAsrani** [comment]
It should be fixed with: https://github.com/WordPress/gutenberg/issues/16411

**Comment by HardeepAsrani** [comment]
@rodica-andronache Normally Read More shouldn't be used inside a nested block as it will break the HTML structure. It should only be used in the root level.

**Comment by rodica-andronache** [comment]
@HardeepAsrani ok, thanks 👍 didn't know that
