### ISSUE TITLE
Option to Remove Background Shadow on Post Grid Images

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#146]
Otter adds a default box-shadow to post grid images which is not always needed. 

We can offer a way of disabling the box-shadow for it.

Ref:  https://www.notion.so/themeisle/b34a97fcf6e6441fb3c826e384155a91?v=bf5353a18d6946d184201e7c114c2466&p=f193b133a5454aa195b1533b51cbf40d

**Comment by HardeepAsrani** [comment]
@selul I'm not sure about this as this is something that should be done with the CSS. Weird to have an option just to disable box-shadow. What do you think?

**Comment by selul** [comment]
Yes, it's fine.

**Comment by HardeepAsrani** [comment]
@selul What does that mean? It's fine to add it or not ad it? 😄

**Comment by selul** [comment]
yes, it's fine to add it. an alternative would be to have a range slider around this, i.e from 0 -> 30 where 0 means no border and 30 means a more accentuate border. 

We have this also in neve/hestia this kind of control if you want to check this out.

**Comment by HardeepAsrani** [comment]
Alright, I'll add a way to disable this.
