### ISSUE TITLE
Button Group Inconsitency

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#209]
There is small inconsistency when using Neve and Otter for Button group. 

When you create a button group, in frontend it has a border underline while in frontend it does not. 

Looking at this, I think this might not be only related to Neve, even if the CSS code for the underline is added by Neve due to the fact that Otter don't use core classes for buttons.

If we add `wp-block-button` to the group wrapper and `wp-block-button__link` to the anchor tag it should solve the issues keep the consistency with other themes as well which style the core classes for buttons. 

https://share.getcloudapp.com/xQu01zDp

What do you think @HardeepAsrani

**Comment by selul** [comment]
Also, Otter forces a font size for buttons, making them bigger than it should. https://share.getcloudapp.com/Jru7rG4A

**Comment by HardeepAsrani** [comment]
> If we add wp-block-button to the group wrapper and wp-block-button__link to the anchor tag it should solve the issues keep the consistency with other themes as well which style the core classes for buttons.

Those classes are used by Button block of Core so we shouldn't be using the same classes. For the font, we can't change the default value, unfortunately, but we can use defaults from Customizer with global defaults to solve this.

**Comment by selul** [comment]
@HardeepAsrani why we can't use the core classes? Most of the themes will style those classes and will be a good opportunity to work with our block too.

**Comment by HardeepAsrani** [comment]
@selul This way we will have to maintain our block whenever they make any changes to the code block, and can cause unintended customization, as in someone customizer the core block without wanting to do it in Button Group.

It's a vendor classname, not a universal.

**Comment by selul** [comment]
@HardeepAsrani if the core changes something related to that class, all certain all the themes/plugins that styled that class will have problems, not only us. 

Moreover, I can not imagine how the core will style the core button classes in a way that we would break them.

**Comment by HardeepAsrani** [comment]
@selul I tried this and here's the issue that we're having, even when using normal themes:

Here's how the button block looks:

<img width="715" alt="Screen Shot 2020-02-14 at 11 47 32 PM" src="https://user-images.githubusercontent.com/2649903/74556621-7aa2fa00-4f84-11ea-9eb8-427f192e0c33.png">

Here's how it looks after adding those classes:

<img width="722" alt="Screen Shot 2020-02-14 at 11 43 54 PM" src="https://user-images.githubusercontent.com/2649903/74556637-81ca0800-4f84-11ea-95f6-e50c7d58de7b.png">

That's the thing. Those classes are made for that basic button, while our button is more complex, such as Icon settings and spacing. What do you think?

**Comment by selul** [comment]
This is how they look if we remove the default styles and add the correct classes 

https://share.getcloudapp.com/mXuqoBeb

wp-block-button on wrapper div
wp-block-button__link on anchor tag 

and remove the defaults
