### ISSUE TITLE
Allow Customization of Section ID 

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#223]
Right now we can't edit the HTML anchor https://share.getcloudapp.com/xQug42de 

This is especially useful when we build sections that we need to reference with links, like #contact, #pricing .

Right now to do that we need to use a kilometric id.

**Comment by HardeepAsrani** [comment]
@selul Here's the new workflow. By default, the control looks like this:

<img width="281" alt="Screen Shot 2020-02-26 at 5 58 24 PM" src="https://user-images.githubusercontent.com/2649903/75345235-54555680-58c2-11ea-94e5-95d37e22ec30.png">

And when you try to edit, it looks like this:

<img width="278" alt="Screen Shot 2020-02-26 at 5 58 48 PM" src="https://user-images.githubusercontent.com/2649903/75345174-3a1b7880-58c2-11ea-9da1-662b1356e6e9.png">

When you put a duplicate ID (used somewhere else in the same plage), it looks like this:

<img width="271" alt="Screen Shot 2020-02-26 at 5 58 38 PM" src="https://user-images.githubusercontent.com/2649903/75345191-41db1d00-58c2-11ea-8b6d-896ebbec2a80.png">

**Comment by selul** [comment]
Looks good to me !
