### ISSUE TITLE
Re-use New Gradient Control

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#262]
The new gradient control from the core seems more solid than the current one that we use. 

We can look into this and see re-use the same control available in the cover block 
https://share.getcloudapp.com/YEuA2xOd

**Comment by HardeepAsrani** [comment]
Fixed in https://github.com/Codeinwp/gutenberg-blocks/commit/22cb47e4be0279147c0b5ce16683563ff73846d8 - closing the issue as fixed.
