### ISSUE TITLE
Vertical Align in Block Toolbar

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#265]
I see that we people can control the vertical alignment for the section block from here https://share.getcloudapp.com/7KuRG5mO

We should add this to the block context menu as this is much easier to find there. Also, the core block is following the same pattern. 

Also, I would remove the setting from the sidebar area

**Comment by JohnPixle** [comment]
I agree, it can be used in the block's contextual menu. Highly usable.
If so, we can remove it from the sidebar too.

**Comment by HardeepAsrani** [comment]
Okay, so Gutenberg has this control in Core. So if you're using WordPress 5.2 then it will stay the same way as before. If you're using WordPress 5.3 or above then it will be now part of Toolbar.

Hope that's enough? @selul

**Comment by selul** [comment]
yep, lgtm
