### ISSUE TITLE
Toggle/Accordation Block

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#267]
We can consider building a toggle block.

It's a structural element heavily used in the starter sites that we build and will help a lot improve the quality of the ones that we build for gutenberg

**Comment by HardeepAsrani** [comment]
Aren't Tabs & Accordions the same thing? One horizontal and one vertical? Should we make two or just one that will have different styles?

**Comment by selul** [comment]
Yes, we can use the same block for both of them, but I'm not sure how we could name it in this case.

**Comment by HardeepAsrani** [comment]
Yea, that's one issue. We can think about that.

**Comment by HardeepAsrani** [comment]
- Add AMP Support: https://amp.dev/documentation/examples/components/amp-accordion/?format=websites

**Comment by JohnPixle** [comment]
- In [Gutenberg Hub](https://gutenberghub.com/blocks/accordion-block/) you can see an overview of the Accordion block execution of [CoBlocks](https://wordpress.org/plugins/coblocks/).
- [Accordion Blocks](https://wordpress.org/plugins/accordion-blocks/) plugin





> Aren't Tabs & Accordions the same thing? One horizontal and one vertical? Should we make two or just one that will have different styles?

We can discuss about that @HardeepAsrani, normally when you use an accordion/toggle you have the ability to have multiple (vertical) tabs open. I believe we can use just one block and have a horizontal / vertical mode. In vertical mode, it might behave like a toggle.

**Comment by HardeepAsrani** [comment]
@JohnPixle the only reason why we aren't doing this is because Gutenberg will have it in a future version very soon. We can wait for one release and see how things go, else we can always make things keeping the core in mind as to migrate them when needed.

**Comment by selul** [comment]
@HardeepAsrani it's been a few months since we thought about this and still in the upcoming release(5.5) this won't be present and will be a few months to until the next one. Andrei managed to iterate a very simple accordion block for the optimole site https://staging-frontend.optimole.com/pricing/ and I imagine that adding this in Otter won't take more than 1-2 days having a great benefit for the starter sites workflow.

**Comment by JohnPixle** [comment]
> the only reason why we aren't doing this is because Gutenberg will have it in a future version very soon. 
I get it 100%. But I think we will end up using our own block in any case, I don't expect the default one to be flexible enough to use in the demos. And in our case we can execute this as a single block for both accordion and / or tabs.

Would indeed be a benefit for starter sites.
