### ISSUE TITLE
Hover Color for Button Group not saved

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#269]
seems there is an issue with the newest version when the color is saved.
This can be found here https://demo.themeisle.com/neve-charity-gb/
https://share.getcloudapp.com/OAurXD7n
https://share.getcloudapp.com/8LuJAOYe

**Comment by HardeepAsrani** [comment]
@selul I tried adding a hover color and it's working fine: https://demo.themeisle.com/neve-charity-gb/

**Comment by HardeepAsrani** [comment]
Posting it here for reference: https://www.loom.com/share/2ecbda484ac84cc2ab79a48fa879eadb
