### ISSUE TITLE
special chars in post grid

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#28]
@HardeepAsrani looking over the uninstall feedback, there is a recent one which we might need to check:

`Best grid post but can\'t accept special characters in title meta e.g apostrophe`

We might double check and make sure we decode the html entities when we output the content

**Comment by HardeepAsrani** [comment]
@selul Was it for 1.0 or 1.1? I'm not sure but I think I fixed this in 1.1.

**Comment by selul** [comment]
it was sent by an user of 1.1.0

**Comment by HardeepAsrani** [comment]
@selul Fixed, it only affected the backend part only. Anyway, fixed.
