### ISSUE TITLE
Remove Section Outline

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#295]
I see that on section block, not sure if there are any others, we add an unaesthetic outline around them confuses me and looks bad. 

https://share.getcloudapp.com/GGukljrE

I think that without it looks much cleaner.

**Comment by HardeepAsrani** [comment]
@selul It was suggested by Ionut and Radu: https://github.com/Codeinwp/gutenberg-blocks/issues/45 - personally, I find it to look bad and it's not really helpful.

**Comment by selul** [comment]
Yes, let's get rid of it.
