### ISSUE TITLE
Fix Horizontal/Vertical Alignment

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#296]
when using the section horizontal align, there is an inconsistency between frontend and backend on a section with maximum content width. I've tried to outline here: 
https://www.loom.com/share/5a2a649a109645ac8b2abd0e8ad52a2b
Basically, the content should be aligned in editor, like it is in frontend.

**Comment by HardeepAsrani** [comment]
@selul Seems to be cuz of changing Gutenberg CSS. It used to work until 5.3. This is going to be a big headache as it's pretty hard to get the alignment to work.
