### ISSUE TITLE
Test 1.1.1 Version

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#31]
@stefan-cotitosu Here's a list of all the changes:

- [x] Added Typography Option to Block Toolbar in Advanced Heading and Button Group
- [x] Fixed Padding Resizer in Section
- [x] Template Library should work fine in all devices, including category picker and search
- [x] Fixed alignment on span tag, so use Advanced Heading with span tag and see if the alignment works or not.
- [x] Added Line Height option to Button Group
- [x] Added option to collapse button on devices
- [x] Fixed icons in button group. Add Pricing Block and try to add an icon to the button.
- [x] Increased maximum font size limit in Heading
- [x] Fixed Font Weight value from `regular` to `normal`
- [x] Plugin should work just fine with Gutenberg plugin installed in 5.0, without Gutenberg installed in 5.0, and with Gutenberg plugin installed in 4.9.
- [x] Fixed unescaped char in Post Grid Title, so now blog posts should work fine if they have an apostrophe in the title.
- [x] Fixed issue with duplicating blocks that you pointed out.
- [x] Added Left/Right margin to Section and Columns
- [x] Heading alignment should have responsive options now
- [x] Fixed vertical alignment option in Section, which didn't work before.

Given how Gutenberg works, make sure all the pre-made templates that are part of Otter also work in 1.1.1 version.

Let me know if something breaks or if you have any questions, and thank you for testing!

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani On the first point, alignment control is working properly for Advanced Heading block on all devices.

Button collapse is working fine but it doesn't respect the alignment option anymore, when buttons are collapsed.
<img width="1489" alt="neve-button-collapse" src="https://user-images.githubusercontent.com/26867648/51739991-867efe00-209b-11e9-92d5-a504cfcaa544.png">

![neve-button-alignment](https://user-images.githubusercontent.com/26867648/51740004-8c74df00-209b-11e9-8ade-2085f5e79f53.png)

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani Padding resizer works fine if you mean what I've pointed in the screenshot.

The main issue with the section block is the default value for margin and padding on Section block and all inner columns that is still 20px

<img width="815" alt="padding-resizer" src="https://user-images.githubusercontent.com/26867648/51740267-38b6c580-209c-11e9-8ae6-6ca3cf073949.png">

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani I've tried to import one of the new sections, and with this version of the plugin, a wide section looks like this.

Might be an issue with Neve, but it's the same version of the theme, different version of Otter.
Can you please investigate this? 😄 

![otter-bug](https://user-images.githubusercontent.com/26867648/51742506-a2d26900-20a2-11e9-9fc2-b0e8e8e2cfde.png)

cc @abaicus

**Comment by HardeepAsrani** [comment]
Can you send me the JSON file?

**Comment by stefan-cotitosu** [comment]
Sure, you can download them from here.

https://github.com/stefan-cotitosu/neve/tree/development/gutenberg/templates

**Comment by HardeepAsrani** [comment]
Weird, works just fine for me. Can you bring your instance up using ngrok and share the link with me on slack so I could check? @stefan-cotitosu 

<img width="1792" alt="screen shot 2019-01-25 at 4 46 20 pm" src="https://user-images.githubusercontent.com/2649903/51742805-ca382e80-20c0-11e9-99f1-f444ff48f135.png">

**Comment by stefan-cotitosu** [comment]
http://db928f8e.ngrok.io/

**Comment by HardeepAsrani** [comment]
I'm not an expert on Neve, but might be happening because of this? @stefan-cotitosu 

<img width="845" alt="screen shot 2019-01-25 at 4 49 13 pm" src="https://user-images.githubusercontent.com/2649903/51742949-361a9700-20c1-11e9-9457-8b6d92521c3a.png">

**Comment by HardeepAsrani** [comment]
Remember when I told you I haven't added Margin Left Right for a reason? I remember it now.

It's because of such cases. The `container` layout uses a `margin-left: calc(50% - 50vw);` to make sure the section is aligned full width, while if the default `margin-left` is `0px` which replaces the Neve's margin.

So what do you think we should do? Remove the left/right margin, or expect people to use full width templates? 😄

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu You can move forward with other tests, I'll take care of this one.

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani The control for margin left/right on inner columns breaks the Columns gap control on Section block.

Better to remove any left/right margin I guess.

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu Yes, I know that so we can work around it the same way Elementor does and keep. 😄

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani 

```
Template Library should work fine in all devices, including category picker and search
```

Search and category works fine. What do you mean by all devices? Should I try to import something on an iPad? 😄

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu No, the layout. Just make sure the Cateogry select, search, close buttons and tab are all there and work in mobiles and tablets.

If you check the 1.1 version, category select doesn't work on mobile/tablet devices.

**Comment by stefan-cotitosu** [comment]
Why would you need this to work on the iPad?

I barely build something in Gutenberg on the computer. On iPad it would be harder.

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu Gutenberg is responsive so you can build it on an iPad, even if it's hard. Also, the user can just import the template easily instead of building the page. 😄

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani I am done with testing.

I skipped these steps for now
- Plugin should work just fine with Gutenberg plugin installed in 5.0, without Gutenberg installed in 5.0, and with Gutenberg plugin installed in 4.9.
- make sure all the pre-made templates that are part of Otter also work in 1.1.1 version.

Please let me know when you are done with the feedback above, especially with removing the margin left/right control.
Then I can fix the sections that I already built for Neve and test those cases too 👍

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu Did you try the ```Added Typography Option to Block Toolbar in Advanced Heading and Button Group```?

**Comment by stefan-cotitosu** [comment]
Yes, it works fine.

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani Can you please add responsive alignment for the sharing icons module?

Also, Instagram icon would be great 👍

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu Instagram icon? It's a sharing block so we can't share something on Instagram. 😄

**Comment by stefan-cotitosu** [comment]
Fair enough. Still want the responsive alignment 😄

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu Knew about it but never fixed it. 😄 I guess I should get this one done. 😛

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani For the Advanced Heading block, font-size shouldn't be under typography settings?

Now it's in the Color Settings menu/drop-down

**Comment by HardeepAsrani** [comment]
Closing.
