### ISSUE TITLE
Otter templates have a white  background in the editor when using Gutenberg

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/gutenberg-blocks#317]
When the Gutenberg plugin is installed, some of the templates have a white background in the editor
![Screenshot (1)](https://user-images.githubusercontent.com/3266155/83248416-b2d5ed80-a1ad-11ea-9d62-5788028e7cc2.png)
![Screenshot (3)](https://user-images.githubusercontent.com/3266155/83248420-b36e8400-a1ad-11ea-932e-0b9d7098a85b.png)
![Screenshot (4)](https://user-images.githubusercontent.com/3266155/83248422-b49fb100-a1ad-11ea-9901-2ea6bb5977d9.png)

**Comment by HardeepAsrani** [comment]
Fixed in https://github.com/Codeinwp/gutenberg-blocks/pull/316
