### ISSUE TITLE
Add Box Shadow to Image

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#34]
An Image Block as WordPress' core Image block isn't good for creating templates. We can inspire it from Material Kit.

**Comment by HardeepAsrani** [comment]
Is an Image Card block still needed for making templates or the current blocks are enough for all scenarios? @mghenciu

**Comment by mghenciu** [comment]
@HardeepAsrani 
If it's an Image Box, then yes it would still make sense. Could be used as an Icon Box also, in future.
For sections like this (the content & image are binded together): 
![image](https://user-images.githubusercontent.com/52494172/118250438-27816500-b4af-11eb-9b76-e3d3ddf8de2c.png)

If it's just an image block, I think we are ok, for now. The only things we are missing now for images are the shadow options, more control for border radius & the default Gb bottom-margin (which is annoying). 
Other than this, the default image block, does the job.

**Comment by HardeepAsrani** [comment]
@mghenciu Maybe we can just add those options to the default image block? Will that be fine?

**Comment by mghenciu** [comment]
@HardeepAsrani , I guess we can do that, if the workflow (for people using blocks) doesn't gets too complicated.
The important thing here is that they have to be independent. Meaning that if I use an Image Block, add Shadow to that image (which comes from Otter Blocks) and later deactivate Otter, it shouldn't crash the Image Block. Or at least that's how I see it.

**Comment by HardeepAsrani** [comment]
It won't crash the block, just the options will give away. You can give me list of the options you need for image.

**Comment by mghenciu** [comment]
Awesome!

As mentioned earlier (for now):
- shadow options (in Elementor it's called Box Shadow)
- border-radius options (this is an example where we used it)
![image](https://user-images.githubusercontent.com/52494172/118514002-d8e8fa80-b73c-11eb-958f-c5d479957eb7.png)

**Comment by mghenciu** [comment]
and fyi, Gutenberg adds by default a 1em bottom-margin to Image Blocks
![Screenshot 2021-05-17 at 18 26 17](https://user-images.githubusercontent.com/52494172/118515177-d3d87b00-b73d-11eb-9890-0554eb3ffa04.png)

**Comment by HardeepAsrani** [comment]
Is border option also needed?

**Comment by mghenciu** [comment]
> Is border option also needed?

I don't think border is a priority now. Or at least we didn't used it on images, even on our Elementor demos.

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu,@HardeepAsrani, the shadow option should look like the one from Advanced Heading﻿

**Comment by mghenciu** [comment]
> @mghenciu,@HardeepAsrani, the shadow option should look like the one from Advanced Heading﻿?

Yes @Soare-Robert-Daniel , we need the same controls for Shadow as in the Advanced Heading (color, opacity, blur & positioning).
