### ISSUE TITLE
Posts Chronological

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#376]
There's something wrong with the chronology of Posts block, as described here: https://wordpress.org/support/topic/post-grid-chronological-display/ - I wasn't able to reproduce this so we need to first reproduce it and find out why.

**Comment by HardeepAsrani** [comment]
Can you try @rodica-andronache? I've tried to reproduce it and wasn't able to. :( Both 1 & 2nd issue.

**Comment by rodica-andronache** [comment]
@HardeepAsrani I was able to reproduce just the first issue.
Here's a video of it
https://www.loom.com/share/99b4cec386db474b9b67fff9c706577a
https://wealthy-grouse.jurassic.ninja/test-page/
user:demo
pass:5@67B(5y8K8de8mZeSdhs@n)

**Comment by HardeepAsrani** [comment]
Fixed that. The second one didn't happen/ @rodica-andronache

**Comment by rodica-andronache** [comment]
no, I couldn't replicate the second one
