### ISSUE TITLE
Better UI for Sizing Control

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#38]
As everyone is highly confused and frustrated by Sizing Control (the one we use for Padding/Margin), we need to improve its UI.

We can try to give an option to link all the device values together, just an idea.

**Comment by HardeepAsrani** [comment]
As pointed out by few, Padding and Margin controls are a pain point. Here are few ways to make it better:

- An option to disable it, in case user doesn't want to use padding/margin at all.
- Have an option to link all three views together and change them at once, which will be very confusing for the user.
- The best option (which should have been the default): to use the Desktop sizes for all the screen sizes if they're not selected by the user instead of having a default for tablets/mobiles. 

What do you think @radu-themeisle @selul @abaicus ?

**Comment by HardeepAsrani** [comment]
We always have the 4th option to not do anything until we have more feedback from users. 😄

**Comment by radu-themeisle** [comment]
cc @stefan-cotitosu

**Comment by radu-themeisle** [comment]
My opinion is we should use option 3: use the Desktop sizes for all the screen sizes by default,.

**Comment by stefan-cotitosu** [comment]
I agree with option 3, use Desktop values for all devices until they change 👍

**Comment by HardeepAsrani** [comment]
How's this? Should we make similar UI or keep the current one? @radu-themeisle @stefan-cotitosu 

![sizing](https://user-images.githubusercontent.com/2649903/53689397-02dfbd80-3d7b-11e9-801f-d27eb91d9af0.gif)

**Comment by radu-themeisle** [comment]
I like the current on

**Comment by stefan-cotitosu** [comment]
I like the current approach 🙂

**Comment by HardeepAsrani** [comment]
@radu-themeisle @stefan-cotitosu So you like four different sliders? The reason is that it can be hard to modify all four of them quickly as you need to use the mouse, while Elementor one can work quickly with tabs.

I want to redesign it and thought everyone feels the same, but it appears I'm wrong. 😄  Let me know your feedback.

**Comment by HardeepAsrani** [comment]
cc @rodica-andronache @abaicus @ineagu @selul

**Comment by rodica-andronache** [comment]
I like more Elementor's approach :)

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani I like the current design with 4 sliders, and 1 slider when the values are linked. For me it's easier to modify them this way because the inputs have enough space between them, and if I want to quickly change the values for all devices, it's hard to click in the wrong field before typing with all that space between them. Plus, if I want to try 20px vs 50px for a column, just to see how it looks, it's easier with the slider than using the input arrows (which is the only way in Elementor). By dragging the slider you see the difference quicker, like it's with Advance Column Resize.

I am not saying to not redesign it, it's just my opinion 🙂

**Comment by HardeepAsrani** [comment]
@radu-themeisle @stefan-cotitosu In the last meeting, @selul and I decided to redo the Sizing control with a better Elementor/Photoshop like UI but at the same time, I wanted to make sure that your feedback should be valued as it made solid sense.

So here's the design I've made, which should satisfy both points:

![Sizing](https://user-images.githubusercontent.com/2649903/56844548-9d6a0200-68cf-11e9-980e-f0e4e29b6fe7.gif)

Excited to know your thoughts. :)

**Comment by radu-themeisle** [comment]
@HardeepAsrani Looks good! I'd remove the control input to the right of the selector bar, but I don't mind it that much. I'd also like, if it's not already done, for you to make the selector move while changing the value. So if I'm increasing/decreasing the value using the up/down arrow keys then the "dot" would also move (we can do it later I don't think it's that important for now)

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani It looks good 👍 
I am glad that we still have the slider as I liked the old UI as well 😄 

For me, it does make sense to have the input on the right bar of the slider. This way would be more clear for all users, which value is changing by the slider. 

I also like Radu's idea of removing it, it would make the whole control cleaner, but for me, it's easier to understand which value is that slider changing, maybe some users will appreciate the input too.

**Comment by HardeepAsrani** [comment]
@radu-themeisle Can you explain this?

> Looks good! I'd remove the control input to the right of the selector bar.

If you mean that the popover should be on the right side then Gutenberg only allows top and bottom. Are you talking about it?

- Dot moves when you change the text input.

**Comment by radu-themeisle** [comment]
I was referring to remove this: http://prntscr.com/nj1nd2
But as Stefan said, we can leave it there, it's ok.

**Comment by HardeepAsrani** [comment]
@radu-themeisle Good idea but alas it's not allowed: https://github.com/WordPress/gutenberg/tree/master/packages/components/src/range-control :(
