### ISSUE TITLE
Progress Bar Block

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/gutenberg-blocks#388]
Opened this ticket to collect some ideas and examples on the progress bar.

Here are some of them
👉🏻 [Motopress.](https://motopress.com/blog/getwid-wordpress-blocks-linear-progress-bar-gutenberg-block/)
👉🏻 [NK progress block](https://wordpress.org/plugins/nk-progress-counter-block/)

I think we can go with very simple settings. Attaching Elementor's as well for reference.

![Screenshot 2020-07-27 at 11 38 49](https://user-images.githubusercontent.com/4193672/88521633-d7a7df00-cffd-11ea-9fbf-859ec77e7446.png)
![Screenshot 2020-07-27 at 11 38 38](https://user-images.githubusercontent.com/4193672/88521638-d971a280-cffd-11ea-9181-1a10e4acea29.png)
![Screenshot 2020-07-27 at 11 39 03](https://user-images.githubusercontent.com/4193672/88521642-db3b6600-cffd-11ea-8a9b-957e1cb1134f.png)

**Comment by HardeepAsrani** [comment]
Progress Bar prepared in HTML: https://codesandbox.io/s/sharp-monad-cis0p?file=/src/index.js

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel We can now start working on the Circular Progress bar: https://github.com/afuersch/css-percentage-circle - this one is pure CSS. We can use that. We can use Style Switcher to add the option to change between Progress to Circular: https://github.com/Codeinwp/gutenberg-blocks/blob/master/src/blocks/google-maps/inspector.js#L128

All the attributes should be the same, where possible.
