### ISSUE TITLE
New Templates

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#39]
We need to add 3 new full-page templates and a couple of section templates for 1.2 release. This needs to be revisited once Image Card and Icon List blocks are completed.

**Comment by HardeepAsrani** [comment]
@radu-themeisle Do you want to take over this once Image Card and Icon List blocks are completed? If you are up for it then we can talk more about it. 😄

**Comment by radu-themeisle** [comment]
It's the same thing we already did with Hestia & Neve templates, right?
I can do it together with @stefan-cotitosu, you can give us more details.

**Comment by HardeepAsrani** [comment]
@radu-themeisle @stefan-cotitosu Yes, it's similar but not entirely. Instead of making section templates, you will be making 3 different full-page templates. Basically, you have to add multiple sections, select them and then export them as a single JSON file.

We will start with this once the Icon List and Image Card block is ready. Here is my suggestion for the three templates.

Material Homepage: https://demo.themeisle.com/hestia-pro-demo-content/material-homepage-elementor/

Mocha Cafe: https://demo.themeisle.com/hestia-pro-demo-content/mocha-elementor/

Rik: https://demo.themeisle.com/hestia-pro-demo-content/rik-elementor/

They don't have to be completely the same and you can change the design according to our needs, like based on limitations of Otter or how you'd like the design to be.

Apart from that, we need to redo our initial templates without fixed padding and using the max-width approach that you suggested. I'd also like you to document the process and standards that you use so we have a basic template for all future uses.

Let me know your thoughts.
