### ISSUE TITLE
Style Blocks

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#4]
Original: https://github.com/Codeinwp/themeisle-companion/pull/298

@radu-themeisle 

You need to put your CSS in each block's style.scss (front-end styles) and editor.scss (editor styles), like this: https://github.com/Codeinwp/gutenberg-blocks/blob/master/blocks/plugin-card/editor.scss

And run `npm run dev` to start the watch process.

A couple of blocks have multiple styles, so make sure you style them properly.

Let me know if you need any help.

**Comment by HardeepAsrani** [comment]
PS: Don't change any HTML without having a migration method else Gutenberg will break for existing users.

**Comment by HardeepAsrani** [comment]
Hope you haven't started on this, as it will change once the Layout Grid is done. That CSS will still work, but with different selectors and probably somewhere else.

**Comment by rodica-andronache** [comment]
@radu-themeisle what this about?

**Comment by radu-themeisle** [comment]
This is about the styling the Gutenberg blocks from Otter Blocks such as: Pricing Table, Our Services, Accordion, About Author, Posts Grid, Testimonials Area (hope I didn't miss one). These blocks come with some styling like rounded borders, box shadows, spacing between cards/testimonials etc. There were some small visually issues to be sorted out.
I'm not sure where we stand on Blocks being styled vs letting the theme handle it.

**Comment by HardeepAsrani** [comment]
I don't think we need them, as they will be removed and replaced by Advanced Columns so don't need CSS now. 😄
