### ISSUE TITLE
Button group alignment doesn't work as expected

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/gutenberg-blocks#401]
Repro:
1. Update Otter to version 1.5.6
2. Go to this demo https://demosites.io/laundry-services-gb/ 
3. Notice the Button group alignment, from the Header section on the Homepage

Expected
![image](https://user-images.githubusercontent.com/52494172/89419710-5d343900-d73a-11ea-8177-7088433ff42b.png)

In version 1.5.6
![Screenshot 2020-08-05 at 16 25 28](https://user-images.githubusercontent.com/52494172/89419678-51487700-d73a-11ea-9695-f30a6613c967.png)

**Comment by rodica-andronache** [comment]
might be related to https://github.com/Codeinwp/neve/issues/1870. For me, after going into the editor and save the page, everything is ok

**Comment by mghenciu** [comment]
Thanks Rodica!

Yes, going into the editor and saving the page + Regenerate CSS from Otter options, fixes this problem.

**Comment by HardeepAsrani** [comment]
Should I close it then @mghenciu?

**Comment by selul** [comment]
this is still present and the regenerate issue is still present. 

You can replicate this by building some button group block on the old version of otter and update to the new one after. The style for the button group is lost or somehow not applied. 

It seems that it heals after you manually update the post, by going to editor and click update, BUT NOT when we regenerate the CSS style. 

It seems that the action of updating inside the editor alters the post_content and fix the issues, action that is not done using the regenerate CSS since this is not being done in the backend. 


I have attached the post_content before clicking the update and after and if you run a diff on it you can see that some ids are changed.

[Archive.zip](https://github.com/Codeinwp/gutenberg-blocks/files/5089658/Archive.zip)

@HardeepAsrani how we can fix this? It isn't a solution to ask people to go to their pages and click update.

**Comment by mghenciu** [comment]
After I started manually Re-saving the pages, the alignment for Button-groups it's fixed.
But there is another challenge with border-radius for button-groups. Basically buttons have a 3px border radius, even if in fron-end it looks ok (set to 0) and in customizer the border radius is set to 0.
The border-radius looks to be coming from here: https://s33834.pcdn.co/fitness-trainer-gb/wp-content/themes/neve/style.min.css?ver=2.7.7
@abaicus Maybe you have an idea if this comes from Neve or from Otter.

@selul 
The question now it's should I continue Re-saving pages (to fix the alignment issue) and leave the border-radius for later, or?

Customizer
![image (5)](https://user-images.githubusercontent.com/52494172/91170838-2a021b80-e6e2-11ea-9eb7-506bc0504d3e.png)

Front-end
![image (4)](https://user-images.githubusercontent.com/52494172/91170874-34bcb080-e6e2-11ea-9a08-641c2d4a538a.png)

Live site:
![image (3)](https://user-images.githubusercontent.com/52494172/91170904-41410900-e6e2-11ea-91dc-42b11d9bbc09.png)



**How it should look:**
![image](https://user-images.githubusercontent.com/52494172/91170981-603f9b00-e6e2-11ea-8e71-9a169026d775.png)

**Comment by mghenciu** [comment]
Another thing that's worth mentioning here (regarding the button-group style reset), is that there is a pattern, usually the Reusable Blocks have the style broken - even after you resave the page, but the other ones (not part of a Reusable Block) are fixed after resaving the page.

**Comment by selul** [comment]
@mghenciu how about if you click edit on the reusable block and save them?

**Comment by mghenciu** [comment]
Yep, @selul . Already doing this where we have Reusable blocks (and it works) and I am re-adding the buttons/sections were things don't get fixed after resave. 
Just wanted to bring this up so everyone is aware. I am not sure if this affects users in any way.

**Comment by HardeepAsrani** [comment]
@mghenciu Did you click to Edit the Reusable blocks and then Save? Not the post but the Reusable Block. :)

**Comment by mghenciu** [comment]
@HardeepAsrani Yes, Edit the Reusable blocks and then Save.
And for the pages with no Reusable blocks, Re-saving the post/page fixed the problem (in most cases, because there were some instances where the buttons were empty, so they needed to be rebuild from 0).
And the border-radius issue is still there.

**Comment by HardeepAsrani** [comment]
@mghenciu That is fixed in development and will be fixed in the upcoming release. Hopefully this week.

**Comment by mghenciu** [comment]
@HardeepAsrani , the issue with the buttons aligning to the left after import, 'made his presence' again on 3 demos we tested so far:
https://musical-bobolink.jurassic.ninja/ >>>  original demo: https://demosites.io/photography-gb
https://abundant-tarantula.jurassic.ninja/ >>>  original demo: https://demosites.io/rokophoto-gb/ 
https://demosites.io/laundry-services-gb/

Basically after importing the demos, some buttons are aligned to the left instead of center.

Rokophoto: 
![Screenshot 2021-03-12 at 09 39 19](https://user-images.githubusercontent.com/52494172/110916829-e390a900-8321-11eb-98aa-9d88d019ab44.png)
![Screenshot 2021-03-12 at 09 39 07](https://user-images.githubusercontent.com/52494172/110916831-e4c1d600-8321-11eb-9a3d-1d39a8c9ea28.png)
![Screenshot 2021-03-12 at 09 38 42](https://user-images.githubusercontent.com/52494172/110916838-e7243000-8321-11eb-83ae-848b6a93b333.png)

Laundry Services: https://prnt.sc/10jjrhh

And yes, I resaved the pages but the issue is still present. Will try to regenerate, and see if this fixes the issue.
My question now is if I just should fix this demos (by manually re-building those sections ) or you can look more into it, maybe it's a general issue with all Gb demos? maybe it's worth a Mass 'css regeneration'

cc @tudor-themeisle

**Comment by HardeepAsrani** [comment]
Issue was made here regarding this: https://github.com/Codeinwp/gutenberg-blocks/issues/614
