### ISSUE TITLE
Optimise the Font Awesome Icons background 

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/gutenberg-blocks#433]
**Description**
Currently the container that contains the Font Awesome Icon (when using an Icon block from Otter), expands depending on the icon size. This causes some visual issues, especially when the icons have a different size ratio (see examples below).

**Examples**
How it should look/behave:
![image](https://user-images.githubusercontent.com/52494172/92084064-87c3f100-edcf-11ea-85e4-8653507eaa0c.png)

How it works now:
![Screenshot 2020-09-03 at 10 24 10](https://user-images.githubusercontent.com/52494172/92084167-a88c4680-edcf-11ea-9db0-8393f7c8f3a5.png)

All three icon spans, have different sizes here
![image](https://user-images.githubusercontent.com/52494172/92084517-2fd9ba00-edd0-11ea-817b-11a988a2818a.png)

![Screenshot 2020-09-03 at 10 29 55](https://user-images.githubusercontent.com/52494172/92084728-7d562700-edd0-11ea-8b7e-092ebea49bf8.png)
 
https://demosites.io/podcast-gb/

**Otter version:** 1.5.7

**Comment by Soare-Robert-Daniel** [comment]
@JohnPixle should we make a slider for the user to set the width of the background?

**Comment by JohnPixle** [comment]
> @JohnPixle should we make a slider for the user to set the width of the background?

Hey @Soare-Robert-Daniel, to be honest I am not sure what would be the best approach for the solution here. Can you perhaps take a look at how Elementor handles the icons? Specifically the "stacked" and "framed" view. In their case the background is always in the correct dimensions

Not a CSS expert but I think they seem to specify height and width of 1em.
![Screenshot 2020-09-10 at 18 19 15](https://user-images.githubusercontent.com/4193672/92753055-2c2ad200-f392-11ea-9b10-0731f540ea42.png)

Let me know if you have any questions!

**Comment by Soare-Robert-Daniel** [comment]
I made the` Font Awesome Icons` container to be a box ( the `height` is equal with the `width`). 

![image](https://user-images.githubusercontent.com/17597852/93053690-e19aa580-f670-11ea-969d-94808a0d9604.png)

This simple fix won't work when the `width` will be less than the default `height` of the entire block. 

![image](https://user-images.githubusercontent.com/17597852/93054297-c8debf80-f671-11ea-9d67-a97a4432634d.png)
