### ISSUE TITLE
Be able to edit the text directly on the Progress bar block

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/gutenberg-blocks#456]
**Current behavior**
If you want to modify the Title inside of a progress bar, you have to select the progress bar, and then edit from the side-bar menu

![Screenshot 2020-10-01 at 15 23 51](https://user-images.githubusercontent.com/52494172/94808676-26a53280-03fa-11eb-8e59-632f974a9c8c.png)
 

<br></br>
**For the future**
Have the ability to edit the Title directly in Frontend, so for example here if I click on the Downhill word, I can edit from there. Is not a big deal at the moment, but it should decrease the friction when using/editing this block.

![Screenshot 2020-10-01 at 15 27 41](https://user-images.githubusercontent.com/52494172/94809070-bcd95880-03fa-11eb-86f1-d9b23836e2d3.png)

**Comment by HardeepAsrani** [comment]
Addressed it in the development @mghenciu
