### ISSUE TITLE
No animation for the progress bar if Percentages are set to Hide

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/gutenberg-blocks#457]
I am not sure if this is by design, but if you set the **Show Percentage** to Hide, the progress bar animation is not working anymore. I am not saying that it should work exactly like in Elementor, but I am no seeing the point of showing an empty Progress bar. Maybe @JohnPixle, you have other thoughts. 
Settings view:
![Screenshot 2020-10-02 at 16 00 30](https://user-images.githubusercontent.com/52494172/94925780-73efd580-04c8-11eb-8acb-0d590a2dec63.png)
How it looks in preview:
![image](https://user-images.githubusercontent.com/52494172/94925836-8964ff80-04c8-11eb-9254-5343d32ce48d.png)

<br></br>

Usecase example in **Elementor**
![image](https://user-images.githubusercontent.com/52494172/94925677-4acf4500-04c8-11eb-8563-c33ec88f6627.png)

**Comment by Soare-Robert-Daniel** [comment]
There are still some bugs in the block regarding the functionality in the front-end (another one is when you set duration with 0 ). The fixes will come in the next release ( PR: https://github.com/Codeinwp/gutenberg-blocks/pull/455 ).
