### ISSUE TITLE
Vertical alignment for sections is not working as expected on Otter v1.5.8 (on mobile)

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/gutenberg-blocks#458]
If you try to vertically align items inside a section, the alignment doesn't work as expected -> the items are aligned to top.

Version 1.5.7 (**working as expected**)
![Screenshot 2020-10-05 at 15 13 39](https://user-images.githubusercontent.com/52494172/95078658-29679680-071e-11eb-9728-76ea9109db57.png)
<br></br>
Version 1.5.8 (**not working as expected**)
![Screenshot 2020-10-05 at 15 15 01](https://user-images.githubusercontent.com/52494172/95078685-32586800-071e-11eb-99ba-789ad78a8873.png)

![Screenshot 2020-10-05 at 15 15 15](https://user-images.githubusercontent.com/52494172/95078696-36848580-071e-11eb-8f13-b0042f84c2d7.png)

**Wp**: 5.5.1
**Otter**: 1.5.8
Neve: v2.8.1

**Comment by Soare-Robert-Daniel** [comment]
The alignment for the mobile device was removed after this PR: https://github.com/Codeinwp/gutenberg-blocks/pull/427
The alignment was causing and odd behavior on the Slider Block which makes it unusable.

**Comment by mghenciu** [comment]
Thanks for the quick response @Soare-Robert-Daniel.
Maybe for future releases it would help to have an internal release note (only for cases where some features are removed/deprecated) and the public one (that's added to the changelog).

**Comment by HardeepAsrani** [comment]
I'm closing this as Robert has answered why it was removed. Also thanks for the suggestion of internal release notes @mghenciu - I'll keep that in mind for future releases.
