### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#47]
We can have a Context menu that will add options, similar to Elementor. We can experiment this and see where it goes. 😄

**Comment by HardeepAsrani** [comment]
I was thinking about this, @selul suggested this, and Elementor does a lot of cool stuff using it. But what exactly are we trying to do with this?

Gutenberg has too many stuff going on so we can use, instead of right click, we can use this instead:

<img width="575" alt="screen shot 2019-03-02 at 4 25 36 am" src="https://user-images.githubusercontent.com/2649903/53671173-40711780-3ca3-11e9-86d1-1e63ce3123a6.png">

But what exactly are we going to do with it? Which options are we thinking of? We can add right click but Gutenberg is too filled so it will be too much confusion. 😄

**Comment by selul** [comment]
We can have the same menu as the one you click on the 3 vertical dots should be just fine. 

Wont cause any confusion of sort as those actions are mutually exclusive, you cant have the right click and left click menu on the same time.

**Comment by HardeepAsrani** [comment]
@selul And what will happen to Copy/Cut/Paste/Select All/ and all other browser/addon controls?

And if you go with this, this will also be a feature that can be disabled, right?

**Comment by HardeepAsrani** [comment]
Also looked into this a bit, we can't open that menu with Gutenberg actions, like other things.

The way to go will be to make a custom Menu which will consist of few items, like delete/duplicate and some of the options.

Now the biggest issue is that we can't really use Gutenberg's Component for it but will have to use some jQuery/JavaScript plugin for it as that Tooltip Menu requires there to be a parent element where it opens, while we want to open where the mouse is clicked.

**Comment by HardeepAsrani** [comment]
@ineagu @selul Anything here? Don't see anything major we can do it. Thoughts?
