### ISSUE TITLE
Compatibility with ThemeIsle Icons

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#477]
to avoid loading fa icons, we can provide a list of alternative icons along with the ones from font awesome which are lightweight and don't require loading any external style. 

we can use the svg icons from https://themeisle.com/free-icons/

**Comment by HardeepAsrani** [comment]
@selul I really think that most users will still prefer to have Font Awesome even if that makes their website a bit slows. What do you think?

**Comment by selul** [comment]
I don't think will cause any harm to the experiment. Right now on https://demosites.io/web-agency-gb/ we download the whole font-awesome library just to use one icon :)
