### ISSUE TITLE
themeisle svg icons are not visible

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#531]
The themeisle icons added based on this issue https://github.com/Codeinwp/gutenberg-blocks/issues/477 are not really working on the editor side.

The dropdown doesn't show any preview of them. 
On the editor side, there is no icon present. 

However, on the frontend, the icon is showing fine.
 
![image](https://user-images.githubusercontent.com/3330746/101156524-69210080-3631-11eb-9228-fcfe5c0cdd94.png)

**Comment by selul** [comment]
I'm using a fresh install, with no other plugins and the default theme

**Comment by HardeepAsrani** [comment]
@selul Can you reproduce it on jurassic ninja? I tried to reproduce it but it works properly.

**Comment by selul** [comment]
@HardeepAsrani can you share with me the instance which was working for you?

**Comment by selul** [comment]
seems like this is still bugged, even if we don't use any fa icon on that page, the FA file is still loading. You can replicate it here https://demosites.io/web-agency-gb/

**Comment by HardeepAsrani** [comment]
Fixed in https://github.com/Codeinwp/gutenberg-blocks/pull/538
