### ISSUE TITLE
ThemeIsle Icons are not working as expected in Safari

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/gutenberg-blocks#553]
While using Otter Icon block, if you use ThemeIsle Icon Libary, the icons background looks stretched (see the attachments).
The issue was discovered on Safari v 14.0.2 (15610.3.7.1.10, 15610)
Demo: https://demosites.io/web-agency-gb/

This is how it looks when using **Font Awesome:**
![image](https://user-images.githubusercontent.com/52494172/102802254-0d8b9c80-43bf-11eb-91cc-e6df5ae7a6fb.png)

This is how it looks when using **ThemeIsle Icons:**
![Ztpj56K_](https://user-images.githubusercontent.com/52494172/102802333-2431f380-43bf-11eb-8dd5-2bf345b53ae7.png)

**Comment by HardeepAsrani** [comment]
Fixed in https://github.com/Codeinwp/gutenberg-blocks/pull/528/commits/32e98a4205a57395d7b4aa4682c931dfa77914db - will be out with the next release.
