### ISSUE TITLE
Tools for a better world 

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/gutenberg-blocks#557]
@HardeepAsrani can we add a formatter for Javascript and PHP? Fixing the issues by hand is not that good. Pressing `Ctrl + S` and letting the VS Code to do the job is better.

**Comment by HardeepAsrani** [comment]
Do you want to take this up? Will be really helpful. We do have a formatted when it comes to the command line and you can use VS Extensions to do that but something by default will be good to.

**Comment by Soare-Robert-Daniel** [comment]
I have a setup in LogoMaker with Prettier: https://github.com/Codeinwp/logo-maker/blob/main/.prettierrc.json 
Also the EsLint is coupled with Prettier: https://github.com/Codeinwp/logo-maker/blob/main/.eslintrc.json to make their collaboration 
more smother.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani do you like tabs or spaces? Js with or without semicolon and the end?

**Comment by HardeepAsrani** [comment]
Tabs, Semicolon. We already use ESLint which takes care of most of these: https://github.com/Codeinwp/gutenberg-blocks/blob/master/.eslintrc

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani what do you think about TypeScript? And a migration to it?
