### ISSUE TITLE
Animation not working on Progress Bar Block, after import

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/gutenberg-blocks#628]
There is an issue with the Progress Bar animation, after you import a demo. 
It looks ok when you edit the imported demo in Gutenberg, but in Front-end the animation is not loading + there is an error related to this in the Developer Console.
![image](https://user-images.githubusercontent.com/52494172/112841038-b295cf80-90a8-11eb-89b3-3a76fd9b9c62.png)

One example how the progress bar should look:
![image](https://user-images.githubusercontent.com/52494172/112841711-7ca51b00-90a9-11eb-9f91-859bf55c5cb2.png)

How it looks on an imported demo:
![image](https://user-images.githubusercontent.com/52494172/112841663-6dbe6880-90a9-11eb-9da8-2b7ecf99ae27.png)

Tested on this 2 demos:
https://demosites.io/cv-gb/
https://demosites.io/laundry-services-gb

Video (with demo before Import and after):
https://www.loom.com/share/daa69dc5a44a4dcb8a95ac5a1ba6fdfc

**Comment by HardeepAsrani** [comment]
Duplicate https://github.com/Codeinwp/otter-blocks/issues/438

**Comment by HardeepAsrani** [comment]
Should be fixed. Can you notify the user to update? Thank you for reporting! @mghenciu
