### ISSUE TITLE
Request to add a single layout/column in the section block

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/gutenberg-blocks#630]
When adding a Section block and chose an equal layout, for instance, then change the column to one,
https://vertis.d.pr/irzeAF
This error comes up:
https://vertis.d.pr/z392Jj

One of our users suggested if we can add a single layout to this block.

Ticket: https://secure.helpscout.net/conversation/1460611774/271866/

**Comment by HardeepAsrani** [comment]
Should be fixed. Can you notify the user to update? Thank you for reporting! @purplecodes
