### ISSUE TITLE
extremely slow with Otter/Gutenberg-blocks

### ISSUE THREAD

**Issue by alex29ua** [Codeinwp/gutenberg-blocks#633]
Since yesterday, after editing 2 of my posts, they became extremely slow in rendering. 

Spotted it to Neve theme and Otter-blocks plugin. Using the latest versions of Neve theme and plugin (2.10.4 and 1.6.3).

With all other plugins disabled, it looks like my browser gets almost whole page from the server, then waits for 25s, and then gets the footer part. Checked with curl downloading, the same. 

If I enable my usual plugins, it becomes even worse, whole page doesn't appear before 25-30 seconds. Sometimes resulting in a timeout even. I think, some plugins trying to wait for the whole DOM to be rendered to cache or process it.
 
But anyway, even just this one plugin - and pages are unusable. Other pages at the site are ok. If I try to edit and save them, they become "broken" as well. 
If I "cut" parts of the page, making it smaller - it just becomes gradually faster, but it doesn't seem like there's a specific part of the page that introduces the slow-down, so it's just - the bigger the page, the slower the load. 

Switching to a different theme - it works normally.

**Comment by selul** [comment]
@HardeepAsrani seems like is originating from Otter, do you have any thoughts on it?

**Comment by HardeepAsrani** [comment]
Yes, I read this on forum yesterday and doing some tests to see this is causing any substantial slowness.

**Comment by HardeepAsrani** [comment]
Hey @alex29ua,

We tried to reproduce on our end and weren't able to see any slow speed being caused by Otter, in fact, it was almost the same with or without Otter.

It might be some other issue. If you have a staging site then can you give us access to that so we could see if it's Otter?

Also, I'll recommend you to use Optimole to optimize your images to make your website faster: https://wordpress.org/plugins/optimole-wp/

Let me know!

**Comment by alex29ua** [comment]
Trying some debug for this function. 
It was called 18631 times during the rendering of that page. Page is a bit big, yes, but not really that crazy. 
Other pages at this website only generate about 20 calls. 

Found that if I just take first paragraph of the page and only leave it inside, page calls the mentioned css function 70 times. Each insertion of the same paragraph adds roughly the same amount of calls. 

Paragraph is something auto-generated in the visual editor:

```
<!-- wp:paragraph {"style":{"color":{"background":"#c5facd"}}} -->
<p class="has-background" style="background-color:#c5facd">B</p>
<!-- /wp:paragraph -->

```
And each of this drives the plugin crazy.


Noticed that if I create a paragraph in a new Page, and assign some background color, it now generates a different code, not with three nested `{}`, something with `<!-- wp:paragraph {"backgroundColor":"neve-link-hover-color"} -->`  - and this one is ok even when copied many times in the page. 
But somehow my "broken" page got the paragraphs like in my example, and it misbehaves then. 

Is this helpful? Can you reproduce it?

**Comment by HardeepAsrani** [comment]
@alex29ua Thanks for the additional info. Can you try to navigate to Settings > Otter, and disable the Custom CSS extension to see if the slowness is still there afterward? That will be helpful for us to know. Thank you!

**Comment by alex29ua** [comment]
@HardeepAsrani Disabling it doesn't affect anything, still 18000 of slow `used_css_properties` function calls. For now, I've commented out `array_merge` line from it, otherwise I just get a page timeout mostly.

**Comment by HardeepAsrani** [comment]
@alex29ua can you try to see if you can reproduce this issue on tastewp.com? It's a quick WordPress testing website creator. We have tried many times and can't reproduce this. used_css_properties function call doesn't run as many times for us.

**Comment by HardeepAsrani** [comment]
@alex29ua Did you get my reply to your email?
