### ISSUE TITLE
Test with AMP

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#637]
@irinelenache Can you test and make sure everything in our plugin works with AMP? We want to list our website here: https://amp-wp.org/ecosystem/plugins/

**Comment by irinelenache** [comment]
@HardeepAsrani 

- [ ] the circle counter doesn't load with AMP activated ( https://prnt.sc/1180q91 )
- [ ] The Google Maps Block gives this error with AMP activated ( https://prnt.sc/11816g3 )
- [ ] The progress bar doesn't load correctly:
Editor: https://prnt.sc/1181akl
Front-end: https://prnt.sc/1181aul
- [ ] The slider doesn't work as expected:
Editor: https://prnt.sc/1181h7r
Front-end: https://prnt.sc/1181hz5
- [ ] The animations don't work

**Comment by HardeepAsrani** [comment]
> The slider doesn't work as expected.

Yea, that's normal. It will work like this in AMP.

I will check the rest and see how it goes. Everything else works perfectly? Did you try to Leaflet?

**Comment by HardeepAsrani** [comment]
> The animations don't work

We disable animations on AMP because of CSS size, it makes the page a lot heavier than allowed.

**Comment by irinelenache** [comment]
@HardeepAsrani From my testing everything else works ok, including leaflet

**Comment by HardeepAsrani** [comment]
> The Google Maps Block gives this error with AMP activated ( https://prnt.sc/11816g3 )

It work for me with proper API. I've Slack'd you to test.

**Comment by HardeepAsrani** [comment]
Okay, so Circle & Progress bars don't work and I don't think we can do much about it. What do you think we should do with them? Any thoughts @selul @Soare-Robert-Daniel @irinelenache

**Comment by selul** [comment]
yes, I'm not aware of any AMP components for circle/progress bar, we can just fail-safe for them when on amp and display them just without animation, using just plain CSS as lightweight as possible.

**Comment by Soare-Robert-Daniel** [comment]
Static elements might be a solution.

**Comment by HardeepAsrani** [comment]
Hey @irinelenache,

Can you test Progress and Circular Progress Blocks? I’ve made them AMP ready. Make sure to check all things and see they work in all browsers.

**Comment by irinelenache** [comment]
@HardeepAsrani should i pull the changes from somewhere?
This is how the Progress bar and Circular progress look with AMP:
editor: https://prnt.sc/11p5uve
frontend: https://prnt.sc/11p5vxy

**Comment by HardeepAsrani** [comment]
Sorry @irinelenache, I forgot to push the changes. I've done. You can fetch the development branch.

**Comment by irinelenache** [comment]
@HardeepAsrani  tested again and here is what i found:

- [ ] the circle counter doesn't look ok in frontend
- [ ] the circle counter percentage is smaller than in editor
- [ ] the progress bar doesn't show the percentage
editor: https://prnt.sc/11x49v3
frontend: https://prnt.sc/11x4b4j

**Comment by HardeepAsrani** [comment]
@irinelenache I think the circle is fine. We can only do too much.

**Comment by HardeepAsrani** [comment]
Progress Bar doesn't show properly in one particular setting but rest it works fine too.
