### ISSUE TITLE
[ Dev ] Webpack upgrade

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/gutenberg-blocks#648]
@HardeepAsrani, we should upgrade Webpack to 5.x version. Made some testing on the `bleeding-edge` branch and the changes are significant - some filenames for output are also changed for chunks.

**Comment by HardeepAsrani** [comment]
When you tried, is everything working properly?

**Comment by Soare-Robert-Daniel** [comment]
No, some functionality was eliminated and the chunk system works a little differently. It might involve some modification on the PHP script loader.

**Comment by HardeepAsrani** [comment]
Yea, there were a lot of issues when I last tried to use Webpack 5 on Otter, so it wasn't worth the effort when we have no issues with webpack 4 and so far all the plugins we use are made for version 4.

**Comment by Soare-Robert-Daniel** [comment]
we could test it on this part, in preparation for Typescript.

**Comment by HardeepAsrani** [comment]
Okay, you can test if that works.
