### ISSUE TITLE
Section block changes the column ratio

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/gutenberg-blocks#649]
Here are the steps taken:

1. Created a new page from **WordPress Dashboard** > **Pages** > **Add New**
2. Selected 1:2 layout
3. Configured the columns to 90:10
4. Added some texts and saved the changes
5. Changes are displayed correctly when viewed in the frontpage but when I clicked on Edit page again, the ratio is set to 50:50.

See screencast for reference. 
https://vertis.d.pr/0DpXNj

Ticket: https://secure.helpscout.net/conversation/1471164307/273285/

**Comment by HardeepAsrani** [comment]
I've released a new version, can you see if this works after updating? @purplecodes @performancecoding

**Comment by performancecoding** [comment]
Hello @HardeepAsrani 
Thank you for releasing the new version. I have updated and it appears to work fine, with no sign of automatic changing of column width. Thank you very much

**Comment by purplecodes** [comment]
Hi @HardeepAsrani, thanks for the update. It appears to be working now.

@performancecoding thanks for providing more details and helping us with this issue.
