### ISSUE TITLE
Product Review Block: WooCommerce Data

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#684]
### Product Review’s WooCommerce Integration

This feature will add a new option to the Product Review Block that will allow users to hook the Product Review Block with their WooCommerce products. This will require the block to have a new attribute to store the product’s ID as we will load all other values from Woo product when the page loads. If user adds a product review block in 10 places and then updates the price of their Woo product, we don’t want them to have to do this edit in 10 different places but we want it to be a synced solution.

This feature will only be available to people who are using Neve Pro + WooCommerce. So if someone doesn’t have Neve Pro or Woo installed, this feature will not be available. If the person has used this feature but now not has either of these installed then the feature should stop working while making sure we don’t break the block. In which case, we won’t render anything in the front-end if the user is not admin. For admin, we will show a notice saying this block (both front and back) needs Neve Pro + Woo to be installed.

We can use class_exists( 'WooCommerce' ) and defined( 'NEVE_PRO_VERSION' ) to check if these are installed and activated and pass these down to our scripts.
 As much as possible, we should avoid editing the Review Block and do most of it using Block Editor filters. Of course, some things will require us to edit the review, but mostly placeholders.

Here are the fields that we can get from the product:

- Title
- Price
- Discounted Price
- Currency
- Product Image
- Short Description
- Link

All of these values should be stored as a state instead of attributes as they will be loaded when the page loads. When the data is being loaded, we should make it visible so the user knows that some data is being loaded.   Also, these synced data fields should not be editable from the Product Review block. So all the imported fields should be “read-only” in the editor, while making sure there’s a notice on the top letting users know why they can’t edit and how they can convert it back to a normal block. For making them read-only, we can have an isReadOnly state that can be toggled. Of course, we will have to edit the block code for this. 

WooCommerce Integration panel should also have an “Un-sync” button that will take all the dynamic data, delete the product ID attribute & save the state as attributes.

If the item is sold out then we should show it somehow, we can do by appending (Sold Out) to Link Button.

Make sure the currency field works as expected and we show currency based on the product/site instead of USD for everything, while keeping USD the default fallback.

For testing, use WooCommerce’s sample data CSV file. It has variations and other kinds of products type. Gotta catch ’em all!

Let me know if anything is unclear here.

**Comment by Soare-Robert-Daniel** [comment]
What is the exact workflow for this feature?

We have an option like in figure 1, the user presses the dropdown, selects a product and then a REST API request is sent to WooCommerce for extracting? Should we use JS or PHP for this?

Figure 1:
![68_2](https://user-images.githubusercontent.com/17597852/124430099-6927e100-dd77-11eb-98ae-5fc9bb4be56c.png)

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel

It can be a tab like this if the person is using Neve Pro:

<img width="808" alt="Screenshot 2021-07-05 at 2 41 50 PM" src="https://user-images.githubusercontent.com/2649903/124447587-2417a500-dd9f-11eb-8e7b-d5ca1047b31d.png">

That tab will have a dropdown that user can select one of the products from and the data will be fetched and shown in the review. I've a list above which list what we can import from there. Those fields will become read-only and users won't have any control over those data.

Make sure it's done using filters so that it can remain a separate functionality which only works with Neve Pro, while you can edit the original block to fulfill some conditions (without editing any attributes) to support these changes. It should fetch the latest data on each reload and store it as local state, rather than in attributes.

What do you think? Any questions or improvements?

**Comment by Soare-Robert-Daniel** [comment]
How can I achieve the trick with the filter? Do we have an example for it?

How can we do the auto-update? How do we know if a product belongs to WC? Should we check if the title match?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel 

1. The same way you made the Slider Block extension: https://github.com/Codeinwp/gutenberg-blocks/blob/master/src/plugins/galley-extension/index.js
2. That's simple. Products are a post_type of their own so it will only be a WC product, you can save the post ID as the new attribute.

**Comment by Soare-Robert-Daniel** [comment]
> 2. That's simple. Products are a post_type of their own so it will only be a WC product, you can save the post ID as the new attribute.

When you referred to not edit the block attributes, does it not include adding a new one?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel You can add a new one using the filters but not directly, so that the attribute is only available when used with Neve Pro.

**Comment by selul** [comment]
What we need to account for here is that the data should be in sync maybe? Like when changing a product in woo, the review should change too?

**Comment by HardeepAsrani** [comment]
Yea, that's the plan. All the possible data will be dynamic apart from Pro/Cons & Ratings. I'll be posting a big detailed comment soon.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel I've updated the issue with all the details https://github.com/Codeinwp/gutenberg-blocks/issues/684#issue-899945449 - let me know if anything is missing.
