### ISSUE TITLE
Section Block Background Image - encountered an error and can't be previewed.

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/gutenberg-blocks#710]
If you add a new Section, and add a Background Image to it, there is an error in the console and the Section Block can't be previewed.
Fortunately, if you save and refresh the page, the section works as expected.
[Video](https://www.loom.com/share/3453a998dd6a45018a9884ac0d8883f7)
![Screenshot 2021-06-29 at 14 46 38](https://user-images.githubusercontent.com/52494172/123792450-4a45cc80-d8e9-11eb-98b5-73998206647d.png)

Repro:
1. Create a Wordpress instance
2. Import one of our Gutenberg demos or just install Otter Blocks
3. Add a new section to a Page
4. Set the Section background to a Image

This issue appears only when you start editing the page for the first time. After the first save/refresh, everything looks to be working.
Even if the issue has a low Probability, it's better to have it here.

WordPress 5.7.2 
Otter: Version 1.6.8

**Comment by HardeepAsrani** [comment]
Hey @mghenciu,

I tested it and it works just fine for me. Can you try @irinelenache or @Soare-Robert-Daniel to see if you also face anything like this?

**Comment by Soare-Robert-Daniel** [comment]
Same for me.

**Comment by mghenciu** [comment]
Then it may a NAD (not a defect) and we can close it.
Thanks for checking!

**Comment by HardeepAsrani** [comment]
Closing it now, feel free to reopen if you find a way to reproduce it. Thank you!
