### ISSUE TITLE
Comparison Table for Review Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#722]
Few questions on what we should do:

1. Should it just compare the review blocks which are on that page?
2. Should we extract reviews from posts and make a REST API to do that?
3. Should we use the old design or get a new one to match the Review block?

@selul

**Comment by selul** [comment]
@HardeepAsrani : 

1. Nope.
2. We should be able to build a comparison in the same fashion as on WPPR, people can select one POST/PAGE category or a set of ids and we extract the review that from them.  
3. A fresh design would help, we can use the one from comparison table in neve.
