### ISSUE TITLE
[WP 5.8] Blocks break when they are added into sidebar

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/gutenberg-blocks#726]
Gutenberg blocks break in front-end when they are added into the sidebar, as widgets:

Icon list in editor: https://vertis.d.pr/yA2mR7
Icon list in frontend: https://vertis.d.pr/giC4dH

Circle counter in editor: https://vertis.d.pr/3JUTOC
Circle counter iini frontend: https://vertis.d.pr/62lu94

**Otter version:** 1.6.9
**Wordpress version**: 5.8 RC1

**Comment by HardeepAsrani** [comment]
To add more context here: CSS/JS for the blocks isn't being rendered here as they don't load on a particular post, so we need to make sure they load properly.

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/1578993917/286642
