### ISSUE TITLE
[WP 5.8] Input color from palette doesn't work when the block is added into Neve sidebar

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/gutenberg-blocks#727]
When i add a block into the sidebar as widget, the palette colors are empty:
https://vertis.d.pr/hDGedP

**Otter version:** 1.6.9
**Wordpress version:** 5.8 RC1

**Comment by HardeepAsrani** [comment]
@irinelenache Is it working with Core blocks?

**Comment by irinelenache** [comment]
Same thing happens with core blocks https://vertis.d.pr/LYpQ0G , should i move the issue to Neve? @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@irinelenache Yes but first you should test if other themes work properly.

**Comment by irinelenache** [comment]
Opened another issue in neve repo https://github.com/Codeinwp/neve/issues/2954  . Will close this
