### ISSUE TITLE
User Restrictions Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#731]
A block extension to restrict user based on their device, role and status. Part of https://github.com/Codeinwp/neve-pro-addon/issues/1451

- [x] Everyone
- [x] Logged In
- [x] Logged Out
- [x] User Role
- [x] Post Author
- [x] Posts Meta
- [x] Date Time
- [x] Recurring Days

**Comment by HardeepAsrani** [comment]
What filters should we have here?

- User Login Status
- User Role

Anything else?

- Device?
- Date/Time?
- Country/IP?

@selul

**Comment by selul** [comment]
let's go with expiration date/time and device type too. For device type make sure to avoid targeting the device via PHP, we can do this using CSS for now.

**Comment by HardeepAsrani** [comment]
@selul We take care of things on the server side so CSS classes really won't help. Maybe we can let go of devices for now and focus on other things, categories, post author, and meta (which will be useful in Reusable Blocks).
