### ISSUE TITLE
Woo Add to Cart

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#734]
A block to allow an Add to Card block anywhere on the website. Part of #1451

**Comment by HardeepAsrani** [comment]
Should we go for something like this? https://webartdevelopers.com/blog/wp-content/uploads/2018/06/daily-ui-012-e-commerce-shop-single-item.png @selul

**Comment by HardeepAsrani** [comment]
Few more examples:

- https://cdn.dribbble.com/users/114038/screenshots/3674970/product_card_design_2x.png
- https://bestof.nyc3.digitaloceanspaces.com/devsnap.me/codepen-WxJEJZ.png
- https://kiranworkspace.com/wp-content/uploads/edd/2021/01/product-card2-768x575.jpg
- https://s3.envato.com/files/239120212/preview_screenshot/07_preview7.jpg

**Comment by selul** [comment]
@HardeepAsrani I would go with something more minimal also and we can extend. The most minimalistic would be just the button, the add to cart button but the user should be able to extend it to title/photo/price, etc.

@JohnPixle @mghenciu can help with some wireframes around this.

**Comment by mghenciu** [comment]
Agree with Marius about the minimal approach. As from what I understood, this is more a Button, not a Product Card.

There are already default options from Woo, for example **Hand-picked Products** block or using the Add to Cart shortcode. But the first one doesn't allow to hide the Product Image, and for the shortcode the result doesn't looks very optimal:
![image](https://user-images.githubusercontent.com/52494172/125934395-470d9a25-6128-4fda-a083-59fa9e740a31.png)

So for our case, I would see this as something very useful when building custom Product Pages, where you'll need a Add to Cart button.
I made a few [low-fi examples in Figma](https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=114%3A5). 
The MVP should allow you to add the button linked to a product, have the common style option for buttons like button Alignment, change the Colors, Border Radius. 
And later we can add more options like Button with Icon, show the price inside the button, show product ratings, etc.

Let me know if this makes sense.

**Comment by HardeepAsrani** [comment]
Thanks for the feedback @mghenciu @selul

**Comment by JohnPixle** [comment]
@mghenciu I like the mockups and the minimal approach for this overall.
Needless to mention that by default this button would inherit the `primary button` styles, correct? :)

**Comment by HardeepAsrani** [comment]
@JohnPixle Of course.
