### ISSUE TITLE
Woo Comparison block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#736]
More details will be added soon as we figure out exactly but it'll be based on Neve's comparison block. Part of #1451

**Comment by HardeepAsrani** [comment]
@selul Just to double-check, here the feature will just be a block for enabling the Neve's comparison option or a thing of its own?

**Comment by selul** [comment]
Yes, should be based on Neve's comparison module.

**Comment by Soare-Robert-Daniel** [comment]
How does this work? Is it just a table where the author selects some WC products, and they are shown side-by-side, like this https://docs.themeisle.com/article/1365-comparison-table-in-neve?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel It will basically be a block for users to allow to use Neve's Woo Comparison functionality as a block. It might need us to modify Neve's code, depending on how their function currently works. Will need to look at that too.
