### ISSUE TITLE
Allow decimal rating in Review Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#769]
Related to: https://wordpress.org/support/topic/review-block-how-to-enable-decimal-in-rating/#post-14814942

**Comment by Soare-Robert-Daniel** [comment]
Some good reference: https://codepen.io/nilsemil23/pen/xpjGWp

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel It's fine, WP already has a half-filled star
