### ISSUE TITLE
Otter Blocks CSS & Custom CSS block attribute

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/gutenberg-blocks#785]
Right now, the Blocks CSS of Otter is generated in stylesheets, while the Custom blocks CSS is added separately. 

It would be really helpful if this style was added to the stylesheets as well. For example in Neve Pro, when we add a custom layout that uses the Custom CSS attribute, it does not get pulled in: https://github.com/Codeinwp/neve-pro-addon/issues/1474

From my testing, tweaking some hooks and parsing the custom CSS at the same time with the other blocks CSS would make this work, but I am not sure about the external implications.

**Comment by HardeepAsrani** [comment]
Here @selul - a question for both this & Otter CSS, does it make sense (for optimization/Google) to load a CSS file even if it's a one or two lines of CSS? Or should we, in such cases, render it inline?

**Comment by selul** [comment]
yes, in this case it makes more sense to render inline.

**Comment by HardeepAsrani** [comment]
Any idea how we should decide the threshold for this? Based on characters or bytes?

**Comment by selul** [comment]
I would say bytes, we can have a limit of 10KB maybe?

**Comment by selul** [comment]
maybe we can use the limit from here? https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/

**Comment by HardeepAsrani** [comment]
> 14.6 KB is the upper limit for critical inlined resources to fit within the first RTT. To fit within three RTTs and Google's recommendation, the cutoff is 98 KB.

10kb sounds good to me, we're expecting 20kbs of Gutenberg CSS + more, so 10% threshold seems good. We can check if the file is currently being checked is just 1-2kbs off-limit and include that too, but anything above that can be loaded from the CSS file.

What do you think?

**Comment by HardeepAsrani** [comment]
Oh wait, I get what you mean. We can simply check our limit against the Gutenberg limit you mean? That sounds good too.
