### ISSUE TITLE
Newsletter & Captcha to Form Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#787]
Once we have the contact form ready, we can try with Mailchimp, Sendinblue & Follow It to make Newsletter/Form Feed variants.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani  What will be architecture for this? We save the email from the from in the database and then send email when someone add a post? Something like [this](https://code.tutsplus.com/tutorials/build-a-newsletter-system-with-php-and-mysql--net-5742)

![mail](https://user-images.githubusercontent.com/17597852/132459054-c327e6c7-1b1d-442f-95ef-6044d5857afb.png)
 
@selul, do we have something similar to this?

**Comment by selul** [comment]
@Soare-Robert-Daniel not really, we just forward the email to a 3rd party, we don't do the newsletter sending.

The logic will be mostly the same as the newsletter widget for Elementor from here https://github.com/codeinwp/themeisle-content-forms

**Comment by Soare-Robert-Daniel** [comment]
I see, so the block is just an interface for putting emails in the 3rd party

**Comment by selul** [comment]
yes, exactly, the logic can be reused and improved from the elementor one since we are currently using it in OrbitFox.

**Comment by HardeepAsrani** [comment]
Yea, we don't want to send too many emails from the server and get it marked as spam by email services. We can look into the Elementor widget Marius linked to.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, how should we make this design for the integration?
Looking at the example from @selul, that form requires to specify de provider and API key for each instance that you insert.

![image](https://user-images.githubusercontent.com/17597852/132827320-110f19a0-dc9d-40de-8ad9-75158e280e4a.png)

![image](https://user-images.githubusercontent.com/17597852/132827367-6650f826-ba8b-4e09-9d58-d60a9fa634f3.png)

![image](https://user-images.githubusercontent.com/17597852/132827398-4b2ff1d3-a412-4e1c-b0d3-efe335ab3458.png)

Should we follow the same pattern? Adding some functionally, for example, the List-ID can be a `ControlSelect` that shows the available options ( tried to play with Mailchimp, and the only way to that ID is through API call - which is easy for the average user ).

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Yea, use can select the service and then the Key field appears. Once they enter the key, we can show them the list ID.
