### ISSUE TITLE
Use date format specified in general Wordpress settings

### ISSUE THREAD

**Issue by patrickwasp** [Codeinwp/gutenberg-blocks#792]
The date format is hard-coded to `'j F, Y'` instead of using the format specified in `Settings` -> `General` -> `Date Format`.

I think following the format chosen in settings is a more intuitive and flexible approach. 

https://github.com/Codeinwp/gutenberg-blocks/blob/c58fc700fe616d8b4f6029c109a869257d6daeed/inc/render/class-posts-grid-block.php#L226

**Comment by HardeepAsrani** [comment]
It was fixed by this https://github.com/Codeinwp/gutenberg-blocks/pull/794 - will be fixed in the next release.
