### ISSUE TITLE
Only load templates on latest version

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#84]
Because we will be added and updating templates to fix bugs, I was thinking we should limit the importing of new templates if the user is using an older version of Otter.

If you're using an older version, once you click on Import button you will get a message saying you need to use the latest version of Otter to use Template Library. It will give users an option to Abort the action and update, and another option to "Do it anyway" where they can import the template and experience whatever happens (as a lot of times things won't break).

It's a little inconvenience but a good way to make sure we can be creative with our templates without worrying much about backward compatibility of our plugin, at the same time forcing users to use the latest version of the plugin.

@selul @ineagu

**Comment by HardeepAsrani** [comment]
How's this @ineagu @selul?

<img width="1051" alt="Screen Shot 2019-04-02 at 12 04 51 AM" src="https://user-images.githubusercontent.com/2649903/55351037-fdd96f80-54da-11e9-8e80-f0625c0bba62.png">

**Comment by selul** [comment]
@HardeepAsrani is looking good. What **Update now** is doing ? Redirect or update right away?

**Comment by HardeepAsrani** [comment]
@selul  It'll just take user to the update screen.
