### ISSUE TITLE
Test with Gutenberg 5.3

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#86]
Gutenberg 5.3 brings a lot of UI changes that we need to test the plugin with.

**Comment by HardeepAsrani** [comment]
@radu-themeisle Can you test Otter with Gutenberg 5.3 ( just install Gutenberg plugin from Plugin Directory) and see how things look?

It has brought a lot of new styles so things might look different, so can you see if everything looks good? If something doesn't work or looks good then you can put it on this ticket.

Let me know if you have time for this else I'll assign it to someone else.

**Comment by radu-themeisle** [comment]
@HardeepAsrani I might be able to look into it on Wednesday, but I believe it should be tested at least by 2-3 people to make sure we cover testing from different perspectives

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu Can you also help? This way we have three of us testing it. 😄
