### ISSUE TITLE
Warning: Use of undefined constanc OTTER_BLOCKS_VERSION

### ISSUE THREAD

**Issue by jytou** [Codeinwp/gutenberg-blocks#93]
I have updated hestia yesterday and today I have a problem that seems to be situated in gutenberg-blocks. Whenever I try to edit an article, I get this warning:

><b>Warning</b>:  Use of undefined constant OTTER_BLOCKS_VERSION - assumed 'OTTER_BLOCKS_VERSION' (this will throw an Error in a future version of PHP) in <b>[path]/wp-content/plugins/themeisle-companion/vendor/codeinwp/gutenberg-blocks/class-gutenberg-blocks.php</b> on line <b>175</b><br />

Thanks.

**Comment by HardeepAsrani** [comment]
Thank you for posting this. We will take a look and patch it today.

**Comment by HardeepAsrani** [comment]
We've fixed this in https://github.com/HardeepAsrani/gutenberg-blocks/commit/1b3b3b6f622cd2e8feb49c1ccc0d60317f1157eb and it will be a part of next version of Orbit Fox that ships with Gutenberg Blocks.

In addition, you can also use Otter if you just want to use the Gutenberg blocks: https://wordpress.org/plugins/otter-blocks/ - it doesn't contain this error.
