### ISSUE TITLE
Block animations 

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/gutenberg-blocks#99]
@HardeepAsrani someone mentioned here https://wordpress.org/support/topic/why-we-dont-have-the-motion-effect-in-gutenburg-demo-data/ that we are not replicating the animations we have on the main demo, in the Gutenberg one.
Do you know if we'd add something like this in Otter? Or we should use https://wordpress.org/plugins/block-animation/? What do you think? 💯

**Comment by HardeepAsrani** [comment]
It's ready and we just need to test it. You can download the test version here: https://drive.google.com/file/d/16nhao89MHWN2Q-a0OaRZUxTlmQD1sOIo/view?usp=sharing

Here's a video of how it works: https://www.loom.com/share/4ab184be618544ff805225ad09f15e72

Can you help in testing it @radu-themeisle? It shouldn't take more than 5-10 minutes, given it's a very small feature.

We would also love your feedback @mjza on this if you also have time to test it. If you do, please do it on a sandbox like http://jurassic.ninja/ or http://poopy.life/, and not your production site.

**Comment by radu-themeisle** [comment]
@HardeepAsrani Everything looks good, works like a charm 👍

**Comment by mjza** [comment]
@HardeepAsrani Dear Hardeep unfortunately my server is down from yesterday and can not test it at the moment. But I promise to test the product fully with different blocks and in different screen size as soon as you went live.

**Comment by HardeepAsrani** [comment]
@mjza You can try it now: https://wordpress.org/plugins/blocks-animation/
